Fix `snakeCaseToCamelCase` for numbers
lightningdevkit/ldk-swift pull request #97
Opened 2023-01-30 22:54 UTC by tnull

Fixed #96

2023-01-30 23:07 UTC, arik-so requested changes
Would you mind adding a couple generator tests for this?

2023-01-31 17:56 UTC, tnull commented
> Would you mind adding a couple generator tests for this?

Now fixed the test cases that were failing in `HEAD`, and added a test case for `FeeEstimator`, covering `getEstSatPer1000Weight`.

2023-01-31 18:39 UTC, arik-so commented
A bunch of the JS tests are unfortunately still failing for me, but that's because we don't have the lightning_01.h file available to them. That file is available here: https://github.com/arik-so/ldk-parser/blob/main/res/lightning_01.h

Let's copy it to `./test/fixtures/lightning_01.h` and edit all the generator and parser tests to refer to it from that location. It might also be helpful to add an `npm test` step to a Github action, might as well do it in here to let CI make sure tests pass.

I apologize for the scope creep.

2023-01-31 18:53 UTC, arik-so commented on test/fixtures/lightning_01.h
> +../../ldk-c-bindings/lightning-c-bindings/include/lightning.h
wait, no, this looks like a symlink. It should be the actual file

2023-01-31 18:57 UTC, tnull commented on test/fixtures/lightning_01.h
> +../../ldk-c-bindings/lightning-c-bindings/include/lightning.h
Yes, already fixed. Pushed before realizing my error.

2023-01-31 19:40 UTC, arik-so approved these changes

2023-01-31 22:59 UTC, merged